import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { NdjsonDecoder } from '../src/framing.mjs';
const manifestUrl=new URL('../../../../crates/rebon-plugin-protocol/tests/fixtures/v1/manifest.json',import.meta.url);
function source(desc){if(desc.ascii!==undefined)return Buffer.from(desc.ascii);if(desc.hex)return Buffer.from(desc.hex,'hex');const sample={protocol_version:1,host_epoch:0,plugin_id:'p',scope_id:'s',scope_generation:0,call_id:'padding',message:{type:'notification',method:'m',payload:''}};const text=JSON.stringify(sample);const pad=desc.body_bytes-Buffer.byteLength(text);const body=Buffer.from(text.replace('""}}',`"${'x'.repeat(pad)}"}}`));assert.equal(body.length,desc.body_bytes);return Buffer.concat([body,Buffer.from(desc.ending==='crlf'?'\r\n':desc.ending==='lf'?'\n':'')]);}
function normalized(value){const out={host_epoch:value.host_epoch,plugin_id:value.plugin_id,scope_id:value.scope_id,scope_generation:value.scope_generation,call_id:value.call_id,message_type:value.message.type};if(value.message.method!==undefined)out.method=value.message.method;if(value.message.status!==undefined)out.status=value.message.status;const payload=value.message.payload;if(payload?.raw!==undefined)out.payload_raw=payload.raw;if(payload?.n?.raw!==undefined)out.payload_number_raw=payload.n.raw;if(payload&&typeof payload==='object'&&payload.a!==undefined)out.payload={a:payload.a};return out;}
test('shared v1 adversarial exact-byte differential corpus: 67 cases, 67 hashes, zero disagreements',async(t)=>{const manifest=JSON.parse(await readFile(manifestUrl,'utf8'));assert.equal(manifest.version,1);assert.equal(manifest.cases.length,67);let hashes=0,disagreements=0;for(const item of manifest.cases)await t.test(item.name,()=>{const bytes=source(item.source),hash=createHash('sha256').update(bytes).digest('hex');assert.equal(hash,item.sha256);hashes++;const decoder=new NdjsonDecoder();let values=[];const run=()=>{let offset=0;for(const size of item.chunks??[bytes.length]){values.push(...decoder.push(bytes.subarray(offset,Math.min(bytes.length,offset+size))));offset+=size;}if(offset<bytes.length)values.push(...decoder.push(bytes.subarray(offset)));if(item.finish)decoder.finish();};try{if(item.error)assert.throws(run,{code:item.error});else{run();decoder.finish();assert.equal(values.length,item.accept);if(item.expected)assert.deepEqual(normalized(values[0]),item.expected);}}catch(error){disagreements++;throw error;}});assert.equal(hashes,67);assert.equal(disagreements,0);});
