import test from 'node:test';import assert from 'node:assert/strict';
import { CallLedger } from '../src/lifecycle.mjs';import { cancel, chunk, terminal } from '../src/protocol.mjs';
const id=(call_id='c',over={})=>({host_epoch:7,plugin_id:'p',scope_id:'s',scope_generation:3,call_id,...over});
test('scope generations establish, equal-idempotent, jump, regress',()=>{const l=new CallLedger(7);assert.equal(l.advanceScope('p','s',3),'established');assert.equal(l.advanceScope('p','s',3),'idempotent');assert.equal(l.closeScope('p','s',4),'advanced');assert.throws(()=>l.advanceScope('p','s',3),{code:'scope_generation_regression'});assert.equal(l.advanceScope('p','s',4,true),'updated');});
test('global call id cannot be reused',()=>{const l=new CallLedger(7);l.advanceScope('p','s',3);l.register(id(),'inbound','owner');assert.throws(()=>l.register(id('c'),'inbound','owner'),{code:'call_id_reused'});});
test('first terminal wins among all statuses',()=>{for(const first of ['success','error','cancelled']){const l=new CallLedger(7);l.advanceScope('p','s',3);l.register(id(first),'inbound','owner');assert.equal(l.terminal(terminal(id(first),first,null),'inbound').committed,first);assert.throws(()=>l.terminal(terminal(id(first),'error',null),'inbound'),{code:'duplicate_terminal'});}});
test('cancel intent is separate and idempotent',()=>{const l=new CallLedger(7);l.advanceScope('p','s',3);l.register(id(),'outbound','owner');assert.deepEqual(l.cancel(cancel(id())),{accepted:true});assert.deepEqual(l.cancel(cancel(id())),{accepted:true});assert.equal(l.terminal(terminal(id(),'success',null),'outbound').committed,'success');assert.deepEqual(l.cancel(cancel(id())),{accepted:true});});
test('stale drops without mutation; future and unknown reject',()=>{const l=new CallLedger(7);l.advanceScope('p','s',3);l.register(id(),'outbound','owner');assert.deepEqual(l.terminal(terminal(id('c',{host_epoch:6}),'error',null),'outbound'),{stale:'host_epoch'});assert.throws(()=>l.terminal(terminal(id('c',{host_epoch:8}),'error',null),'outbound'),{code:'future_host_epoch'});assert.equal(l.terminal(terminal(id(),'success',null),'outbound').committed,'success');});
test('full identity mismatch rejects before terminal mutation',()=>{const l=new CallLedger(7);l.advanceScope('p','s',3);l.register(id(),'outbound','owner');assert.throws(()=>l.terminal(terminal(id('c',{scope_id:'other'}),'success',null),'outbound'),{code:'identity_mismatch'});assert.equal(l.terminal(terminal(id(),'error',null),'outbound').committed,'error');});
test('terminal direction cannot settle the opposite call class',()=>{const l=new CallLedger(7);l.advanceScope('p','s',3);l.register(id(),'outbound','owner');assert.throws(()=>l.terminal(terminal(id(),'success',null),'inbound'),{code:'direction_mismatch'});assert.equal(l.terminal(terminal(id(),'success',null),'outbound').committed,'success');});
test('scope keys preserve embedded NUL without aliasing',()=>{const l=new CallLedger(7);l.advanceScope('a\u0000b','c',1);l.advanceScope('a','b\u0000c',2);assert.deepEqual(l.scopeGeneration('a\u0000b','c'),{generation:1,open:true});assert.deepEqual(l.scopeGeneration('a','b\u0000c'),{generation:2,open:true});});
test('outbound admission classifies unknown stale future closed and bad directions',()=>{const l=new CallLedger(7);assert.throws(()=>l.register(id('unknown'),'outbound','owner'),{code:'unknown_scope'});l.advanceScope('p','s',3);assert.throws(()=>l.register(id('stale',{scope_generation:2}),'outbound','owner'),{code:'stale_identity'});assert.throws(()=>l.register(id('future',{scope_generation:4}),'outbound','owner'),{code:'future_scope_generation'});assert.throws(()=>l.register(id('bad'),'sideways','owner'),{code:'bad_direction'});l.closeScope('p','s',4);assert.throws(()=>l.register(id('closed',{scope_generation:4}),'outbound','owner'),{code:'scope_closed'});});
test('outbound terminals classify stale scope before mutating current calls',()=>{const l=new CallLedger(7);l.advanceScope('p','s',3);l.register(id('old'),'outbound','owner');l.advanceScope('p','s',4);assert.deepEqual(l.terminal(terminal(id('old'),'success',null),'outbound'),{stale:'scope_generation'});l.register(id('current',{scope_generation:4}),'outbound','owner');assert.throws(()=>l.terminal(terminal(id('current',{scope_generation:5}),'success',null),'outbound'),{code:'future_scope_generation'});assert.equal(l.terminal(terminal(id('current',{scope_generation:4}),'success',null),'outbound').committed,'success');assert.throws(()=>l.terminal(terminal(id('other',{scope_generation:4}),'success',null),'sideways'),{code:'bad_direction'});});

// A call may carry any number of chunks and still exactly one terminal.
test('chunks do not consume the terminal slot and leave no residue',()=>{const l=new CallLedger(7);l.advanceScope('p','s',3);l.register(id(),'inbound','owner');for(let i=0;i<1000;i++)assert.deepEqual(l.chunk(chunk(id(),{i}),'inbound'),{accepted:true});assert.equal(l.terminal(terminal(id(),'success',null),'inbound').committed,'success');});

// Not a late arrival to drop: a duplicate terminal is a race two peers can lose,
// but a chunk after the end means the producer kept emitting after saying it was
// done.
test('a chunk after the terminal is an error',()=>{const l=new CallLedger(7);l.advanceScope('p','s',3);l.register(id(),'inbound','owner');l.terminal(terminal(id(),'success',null),'inbound');assert.throws(()=>l.chunk(chunk(id(),null),'inbound'),{code:'chunk_after_terminal'});});

test('a chunk classifies unknown, stale, direction and shape like every other frame',()=>{const l=new CallLedger(7);l.advanceScope('p','s',3);assert.throws(()=>l.chunk(chunk(id('nope'),null),'inbound'),{code:'unknown_call'});l.register(id(),'inbound','owner');assert.deepEqual(l.chunk(chunk(id('c',{host_epoch:6}),null),'inbound'),{stale:'host_epoch'});assert.throws(()=>l.chunk(chunk(id(),null),'outbound'),{code:'direction_mismatch'});assert.throws(()=>l.chunk(terminal(id(),'success',null),'inbound'),{code:'not_chunk'});});

test('a chunk from a past scope incarnation is stale',()=>{const l=new CallLedger(7);l.advanceScope('p','s',3);l.register(id(),'inbound','owner');l.advanceScope('p','s',4);assert.deepEqual(l.chunk(chunk(id(),null),'inbound'),{stale:'scope_generation'});});
