/* Generated by `cargo run -p rebon-schema-gen` from the Rust definitions in
 * `crates/rebon-proto` and `crates/rebon-types`. Do not edit by hand — a
 * change made here is overwritten by the next run, and the staleness test
 * `generated_files_are_current` fails until the two agree.
 *
 * An optional field reads `field?: T` with no `| null`, because the `Option`
 * behind it carries `skip_serializing_if = "Option::is_none"` and the server
 * leaves the key out rather than sending null. A field that really does send
 * null says so — `oldText: string | null`. The test
 * `optional_fields_are_omitted_not_nulled` keeps the two apart. */

/** Any JSON, as `serde_json::Value` reaches the wire. */
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

/**
 * What the four `/api/*` levers answer: task cancel and dismiss, MCP
 * reconnect and disconnect, a rewind, a compaction.
 *
 * `ok` is whether the thing was done, not whether the request was
 * understood — a request that was not understood is a 400 with a reason and
 * never reaches this shape.
 */
export interface ActionResult {
  /** What to show the person who asked. */
  message: string;
  /** Whether it happened. */
  ok: boolean;
  /**
   * A rewind hands back the prompt of the turn it rewound to, so the
   * composer can be refilled with it. Absent on every other lever, and on
   * a rewind the owner performed.
   */
  prefillPrompt?: string;
  /**
   * How many turns the rewound conversation has left. Absent for the
   * same reason.
   */
  turns?: number;
}

export interface AgentCapabilities {
  _meta?: Record<string, JsonValue>;
  loadSession?: boolean;
  mcpCapabilities?: McpCapabilities;
  promptCapabilities?: PromptCapabilities;
  sessionCapabilities?: SessionCapabilities;
}

/** One entry of [`AgentsResponse::agents`]. */
export interface AgentEntry {
  /** Whether it runs in the background by default. */
  background: boolean;
  /** When to use it, from the definition's own words. */
  description: string;
  /** The reasoning effort it pins, or `null`. */
  effort?: string;
  /** The model it pins, or `null` to follow the session's. */
  model?: string;
  /** The agent type, which is what a spawn names. */
  name: string;
  /** The provider it pins, or `null`. */
  provider?: string;
  /** Which runtime runs it. */
  runtime: string;
  /**
   * Where the definition came from: `builtin`, `plugin:<name>`, `user`,
   * `project`, `local`, `flag`, `policy`.
   */
  source: string;
  /** The tools it is allowed, or `null` for the default set. */
  tools?: string[];
}

/** One entry of [`ServerInfo::agents`]. */
export interface AgentOption {
  /** The value to set the agent config option to. */
  id: string;
  /** What to show in the picker. */
  label: string;
}

/** `GET /api/agents`. */
export interface AgentsResponse {
  /** Every agent definition this server can run. */
  agents: AgentEntry[];
}

/**
 * [`method::ANSWER_QUESTIONS`]: the answer to an AskUserQuestion.
 *
 * Its own method rather than the standard permission answer because
 * AskUserQuestion is several questions with several selected options each,
 * and the standard result carries one option id.
 */
export interface AnswerQuestionsParams {
  answers: ForegroundQuestionAnswer[];
  queryId: number;
  /**
   * Fences the answer against the turn that asked. Defaulted for the wire
   * so a peer from before this field reads as turn zero, which is what it
   * always meant.
   */
  turnGeneration?: number;
}

/**
 * A single content block inside an assistant message. Dispatched
 * by the `type` discriminant.
 *
 * The deferred variants (`server_tool_use`, `advisor_tool_result`,
 * `connector_text`, plus any future Anthropic content block
 * variants) fall through to [`AssistantContentBlock::Other`] via
 * `#[serde(other)]`, preserving the raw JSON so legacy rows don't
 * break parsing.
 */
export type AssistantContentBlock =
  | (AssistantTextBlock & { type: "text"; })
  | (AssistantThinkingBlock & { type: "thinking"; })
  | (AssistantRedactedThinkingBlock & { type: "redacted_thinking"; })
  | (AssistantToolUseBlock & { type: "tool_use"; })
  | (AssistantGeneratedImageBlock & { type: "generated_image"; })
  | {
    type: "other";
  };

/**
 * `{ type: 'generated_image', id, status?, revised_prompt?, media_type,
 * data, saved_path? }` — the assistant-side image payload produced by
 * the OpenAI Responses `image_generation` built-in tool. Kept aligned
 * with `rebon_api::GeneratedImageBlock` so transcripts round-trip.
 *
 * Rebon no longer requests that tool (image generation is the `ImageGen`
 * tool now); the block stays so transcripts written before still render.
 * `data` is optional because the engine of that time stripped the base64
 * payload once it had saved the image, leaving `saved_path` as the
 * load-bearing field — the renderer surfaces that and the revised prompt.
 */
export interface AssistantGeneratedImageBlock {
  data?: string;
  id: string;
  media_type?: string;
  revised_prompt?: string;
  saved_path?: string;
  status?: string;
}

/**
 * One assistant row as persisted in a transcript line.
 *
 * Only the fields the renderer reads are modelled; the engine-side
 * bookkeeping (`requestId`, `apiError`, `error`, `errorDetails`,
 * `isVirtual`, `usage`, `message.id`, `message.model`,
 * `message.stop_reason`, `message.container`,
 * `message.context_management`) is not duplicated here — it will
 * land as part of the engine bridge.
 */
export interface AssistantMessage {
  /**
   * `advisorModel` — threaded to advisor rows. Advisor blocks
   * are not rendered yet but the field is preserved so round-trip
   * stays lossless.
   */
  advisorModel?: string;
  /**
   * `isApiErrorMessage` — keeps API error rows visible even in
   * brief-only mode.
   */
  isApiErrorMessage?: boolean;
  /**
   * `Some(true)` on a row minted when the inline overflow flush split
   * one still-streaming text block across scrollback commits. The
   * renderer joins such a row to the previous one — no leading margin,
   * no gutter dot — so the split halves read as a single message.
   */
  isStreamContinuation?: boolean;
  message: AssistantMessageInner;
  timestamp: string;
  uuid: string;
}

/** The `message` sub-object on an assistant row. */
export interface AssistantMessageInner {
  content: AssistantContentBlock[];
  /**
   * Tolerated when absent, for the same reason as
   * [`UserMessageInner::role`].
   */
  role?: AssistantRole;
}

/**
 * `{ type: 'redacted_thinking', data: '...' }` — the renderer shows
 * a `[redacted thinking]` placeholder and never reveals `data`.
 */
export interface AssistantRedactedThinkingBlock {
  data?: string;
}

export type AssistantRole = "assistant";

/** `{ type: 'text', text: '...' }`. */
export interface AssistantTextBlock {
  text: string;
}

/**
 * `{ type: 'thinking', thinking: '...' }` — note the inner field is
 * `thinking`, not `text`, per the Anthropic SDK schema.
 */
export interface AssistantThinkingBlock {
  signature?: string;
  thinking: string;
}

/**
 * `{ type: 'tool_use', id, name, input }`. The `input` is opaque
 * Anthropic-SDK JSON — this code doesn't introspect it; per-tool
 * rendering lands in future renderer extensions.
 */
export interface AssistantToolUseBlock {
  id: string;
  input?: JsonValue;
  name: string;
  /**
   * Raw tool output payload, retained in-memory so rewind can
   * restore file contents for the current session.
   *
   * Also on the wire, and not redundant with `tool_call_content`:
   * `enrich_tool_use_blocks` leaves that `None` for a result with no
   * structured update content, and this is then the only carrier of
   * the output a card has to show.
   */
  raw_output?: JsonValue;
  /**
   * Optional lifecycle status. Set live during a turn and on replay
   * from the matching `tool_result`; serialized when present so a
   * card off the wire can tell a completed call from a failed one.
   */
  status?: ToolCallStatus;
  /**
   * Tool call content payloads (e.g. `Diff` for Edit tools).
   *
   * Populated from the streaming overlay when the tool completes, and
   * on replay by [`crate::transcript_replay::enrich_tool_use_blocks`]
   * from the matching `tool_result`. Serialized when present so a
   * surface reading rows off the wire sees the tool output the
   * terminal sees; absent when there is none, so a row that was never
   * enriched serializes to exactly the bytes it did before.
   */
  tool_call_content?: ToolCallContent[];
}

/**
 * `{ type: 'attachment', attachment: ... }` row wrapper. The inner
 * `attachment` payload is kept as opaque JSON: the rich typed attachment
 * shape lives with the engine, and keeping it opaque here avoids
 * cross-crate type bleed.
 */
export interface AttachmentRow {
  attachment: JsonValue;
  timestamp: string;
  uuid: string;
}

export interface AudioContent {
  annotations?: JsonValue;
  data: string;
  mimeType: string;
  type: "audio";
}

/**
 * One way to authenticate with an agent, as advertised in
 * `initialize`.
 *
 * The spec's shape is `{ id, name, description? }`. Every field is
 * optional here and unknown keys are kept, on purpose: nothing in
 * Rebon reads this yet, and an agent that grows a field would
 * otherwise fail the *whole* handshake over a value nobody looked at.
 * A real agent already broke this once — `@agentclientprotocol/codex-acp`
 * sends `{id, name, description, _meta}`, and requiring a `type` field
 * that the spec never had made `initialize` undecodable.
 */
export interface AuthMethod {
  description?: string;
  id?: string;
  name?: string;
  [key: string]: JsonValue | undefined;
}

/**
 * Which part of the auto-mode gate let a tool call run without a dialog.
 *
 * Display-only, and worth distinguishing because the three are not the same
 * event: a classifier verdict is the machine's judgement, a cached verdict is
 * that judgement replayed, and an exemption is the *user's* own approval — a
 * row that says "auto mode allowed this" over an approval the user gave by
 * hand misattributes it.
 */
export type AutoModeAllowSource = "classifier" | "cachedVerdict" | "userExemption" | "unspecified";

export interface BackgroundIpcCancelFence {
  pendingPermissionQueryId?: number;
  status: BackgroundJobStatus;
  turnGeneration: number;
  updatedAtMs: number;
}

export interface BackgroundIpcEndpoint {
  pid: number;
  port: number;
  token: string;
}

export type BackgroundJobStatus = "queued" | "running" | "needs_input" | "idle" | "succeeded" | "failed" | "stopped";

export interface BackgroundPermissionOptionSnapshot {
  kind: string;
  label: string;
  optionId: string;
}

export interface BackgroundPermissionQuerySnapshot {
  endpoint?: BackgroundIpcEndpoint;
  message?: string;
  metadata?: JsonValue;
  options: BackgroundPermissionOptionSnapshot[];
  queryId: number;
  sessionId?: string;
  title?: string;
  tool?: string;
  toolCallId?: string;
  toolInput?: JsonValue;
  turnGeneration?: number;
}

/**
 * [`method::CANCEL_CALL`].
 *
 * Not a cancel of the *turn*: that is `session/cancel`. This releases one
 * call, because a client timeout that only drops its own receiver leaves the
 * owner working on something nobody will read.
 */
export interface CancelCallParams {
  commandId: string;
}

/**
 * Whether a waiter was actually let go.
 *
 * Always an ok answer: cancelling a call that is not running is not a
 * failure, it is "nothing to release" — which is what a client that raced its
 * own timeout needs to hear.
 */
export interface CancelCallResult {
  released: boolean;
}

/** [`method::CANCEL_TASKS`]. */
export interface CancelTasksParams {
  taskIds?: string[];
}

/** One client holding a session open. */
export interface ClientLease {
  clientId: string;
  kind: ClientLeaseKind;
  pid?: number;
  updatedAtMs: number;
}

/**
 * Which surface a lease belongs to. Carried so `rebon agents` and the Agent
 * View can say *who* is holding a session open rather than only that someone
 * is.
 */
export type ClientLeaseKind = "tui" | "app" | "serve" | "cli";

export interface CommandOutput {
  text: string;
  tone: string;
}

/** [`method::COMPACT`]. */
export interface CompactParams {
  instructions?: string;
}

export interface ConfigOption {
  category?: string;
  currentValue: string;
  description?: string;
  id: string;
  name: string;
  options: ConfigOptionValue[];
  type: ConfigOptionType;
}

export type ConfigOptionType = "select" | "text";

export interface ConfigOptionValue {
  description?: string;
  name: string;
  value: string;
}

/** MCP-compatible content block. */
export type ContentBlock = TextContent | ImageContent | AudioContent | ResourceContent | ResourceLinkContent;

/**
 * Diff content payload — `oldText` may be `null` (when the file did not
 * exist). `old_text` is optional, so the wire form `"oldText": null`
 * round-trips faithfully.
 */
export interface DiffContent {
  newText: string;
  /** **Always serialized** — `null` rather than omitted when `None`. */
  oldText: string | null;
  path: string;
  type: "diff";
}

/** `GET /api/files` — the file picker's candidates for one workspace. */
export interface FilesResponse {
  /** The candidates, a directory marked by a trailing slash. */
  files: string[];
  /** Why the directory could not be listed. Absent when it could. */
  problem?: string;
  /** The directory the paths are relative to. */
  root: string;
  /**
   * Whether the workspace index is still being built, so an empty list
   * means "not yet" rather than "nothing".
   */
  scanning: boolean;
  /** Whether more matched than were returned. */
  truncated: boolean;
}

/** One interactive question (AskUserQuestion), mirrored for the controller. */
export interface ForegroundQuestion {
  header: string;
  multiSelect: boolean;
  options: ForegroundQuestionOption[];
  question: string;
}

/**
 * The controller's answer to one interactive question: chosen option indices
 * plus optional free-form text. With no selected option the text is an Other
 * answer; with selected options it is supplemental notes.
 */
export interface ForegroundQuestionAnswer {
  otherText?: string;
  selectedOptions?: number[];
}

/**
 * One option of an interactive question, mirrored from the engine's
 * `AskUserQuestionOption` so the controller can render it.
 */
export interface ForegroundQuestionOption {
  description: string;
  label: string;
  preview?: string;
}

/**
 * [`method::GAP`]: the owner dropped deltas from its ring.
 *
 * What is missing between `from` and `to` is in the events file, which is the
 * authority; the client reads it from there and resumes. A gap is never an
 * error — an owner that outran a slow client is doing the right thing.
 */
export interface GapParams {
  from: number;
  to: number;
}

/** [`method::HELLO`], the first message on a new subscription. */
export interface HelloParams {
  /** Where the stream is resuming from. */
  cursor: number;
  /**
   * The owner's numbering. It restarts each time an owner starts, so a
   * cursor alone cannot be compared with one written by its predecessor.
   */
  epoch: number;
  status: SessionStatusSnapshot;
}

/** `GET /api/history` — a session as the page reopens it. */
export interface HistorySnapshot {
  /** The directory it belongs to. */
  cwd: string;
  /**
   * **Deprecated.** The model's view of the
   * session, folded a second and different way: it carries tools meant
   * for their own surface, and it deletes a whole user block where the
   * row stream keeps the half a person typed. Nothing first-party reads
   * it; `rows` is what the terminal, the page and the desktop app show.
   */
  messages: JsonValue;
  /** The display rows the terminal draws, from the one producer. */
  rows: JsonValue;
  /** The session read. */
  sessionId: string;
  /** Its title, or `null` for one that has none. */
  title?: string;
}

export interface ImageContent {
  annotations?: JsonValue;
  data: string;
  mimeType: string;
  type: "image";
  uri?: string;
}

export interface ImplementationInfo {
  name: string;
  title?: string;
  version?: string;
}

export interface InitializeResult {
  /**
   * Top-level extension data — a sibling of `agentCapabilities`,
   * not inside it. This is where the steering wire protocol
   * advertises itself: both `claude-agent-acp` and `codex-acp` put
   * `{"steering": {"supported": true}}` here. `default` keeps
   * agents without it decodable, which is also the compatibility
   * story: no `_meta`, no steering, fall back to queueing.
   */
  _meta?: Record<string, JsonValue>;
  agentCapabilities: AgentCapabilities;
  agentInfo?: ImplementationInfo;
  authMethods?: AuthMethod[];
  protocolVersion: number;
}

/** A JSON-RPC 2.0 error object. */
export interface JsonRpcError {
  code: number;
  data?: JsonValue;
  message: string;
}

/** One kernel loop vendor, and whether this session could switch to it. */
export interface KernelLoopOption {
  /** The backend name a switch would name. */
  backendId: string;
  /**
   * Whether this build carries the vendor's assembly. A known but
   * unbundled vendor keeps its seat so the switch can say so loudly
   * instead of "no such vendor".
   */
  bundled: boolean;
  /** Whether a provider and model are configured for it. */
  configured: boolean;
  /** The vendor id: the `/kernel` argument and the config key. */
  id: string;
  /** Human label for the list. */
  label: string;
  /** The configured model, or `null`. */
  model?: string;
  /** The configured provider, or `null`. */
  provider?: string;
  /** Whether the router has this backend to switch to. */
  switchable: boolean;
}

/** [`method::LEASE`]. While any lease is live the owner stays up. */
export interface LeaseParams {
  clientId: string;
  kind: ClientLeaseKind;
}

export interface McpCapabilities {
  http?: boolean;
  sse?: boolean;
}

/** One MCP server. */
export interface McpServerEntry {
  /** The warning naming this server, if one does. */
  error?: string;
  /** The name it is configured or connected under. */
  name: string;
  /** `connected`, `failed`, `not started` or `disconnected`. */
  status: string;
  /** The tool names it contributes, prefixed. Empty unless connected. */
  tools: string[];
  /**
   * `stdio`, `http` or `sse`; `null` for a server that only the client
   * knows about, which is how an env-declared one arrives.
   */
  transport?: string;
}

/** One MCP server the owner has configured, as the owner sees it. */
export interface McpServerSnapshot {
  name: string;
  /**
   * Where the entry came from: the project's `.mcp.json`, the CLI, a
   * plugin.
   */
  source: string;
  /** `stdio`, `http` or `sse`. */
  transport: string;
}

/** `GET /api/mcp` — the MCP servers this process configured and connected. */
export interface McpStatus {
  /** Why the configuration could not be read at all. */
  problem?: string;
  /** One per server, configured or merely connected. */
  servers: McpServerEntry[];
  /**
   * Per-server warnings the loader collected.
   *
   * The server has always sent these; declaring them here changes no
   * bytes and lets the page read them without a cast.
   */
  warnings: string[];
}

/**
 * The owner's MCP servers, for a client that hosts none of its own.
 *
 * Names and states only, never a tool's schema: this rides on every
 * `status` event, and a client shows it rather than calling anything
 * through it.
 */
export interface McpStatusSnapshot {
  /** `ready`, `pending` or `not connected`. */
  client: string;
  error?: string;
  /** `loading`, `ready`, `failed` or `not configured`. */
  loader: string;
  servers?: McpServerSnapshot[];
  tools?: McpToolSnapshot[];
  warnings?: string[];
}

/** One tool the owner's MCP servers offer the model. */
export interface McpToolSnapshot {
  /** The `mcp__<server>__<tool>` name the model calls it by. */
  name: string;
  /** What its definition costs the context, approximately. */
  tokens: number;
}

/** One entry of [`ModelsResponse::models`]. */
export interface ModelOption {
  /** The model id. */
  id: string;
}

/** `GET /api/models` — what this session can be switched to. */
export interface ModelsResponse {
  /** The model id in use. */
  current: string;
  /**
   * Every model the provider offers, the current one first if it is not
   * among them.
   */
  models: ModelOption[];
  /** The active custom provider, or the runtime's own provider name. */
  provider?: string;
}

/** A Node that answered, but not with a version this build accepts. */
export interface OutOfRangeRuntime {
  /** Where it lives. */
  executable: string;
  /** The version it reported. */
  version: string;
}

/** One option offered to the client when the agent asks for permission. */
export interface PermissionOption {
  kind: PermissionOptionKind;
  name: string;
  optionId: string;
}

/** Permission option kind. */
export type PermissionOptionKind = "allow_once" | "allow_always" | "reject_once" | "reject_always";

/** Outcome of a `session/request_permission` round-trip. */
export type PermissionOutcome = "selected" | "cancelled";

export interface PlanEntry {
  content: string;
  priority: PlanEntryPriority;
  status: PlanEntryStatus;
}

export type PlanEntryPriority = "high" | "medium" | "low";

export type PlanEntryStatus = "pending" | "in_progress" | "completed";

/**
 * One entry of the composition, and whether it loaded.
 *
 * A projection of the server's own `ComposeEntry`, not that type: the entry
 * carries a dozen more fields — config, seats, topics, command names — and
 * this listing shows seven of them.
 */
export interface PluginEntry {
  /** The module inside that package. */
  entry: string;
  /** The plugin id. */
  id: string;
  /** LLM providers it declares. */
  llmProviders: string[];
  /** Whether this entry is in the running plane's loaded set. */
  loaded: boolean;
  /** The package it loads from. */
  root: string;
  /** Services it declares. */
  services: string[];
  /** Tools it declares. */
  tools: string[];
}

/** The running plane, or the reasons there is none. */
export interface PluginPlaneStatus {
  /** Which generation it is, or `null` when nothing is running. */
  generation?: number;
  /** The ids that loaded. */
  loaded: string[];
  /** Why the composition could not be read at all. */
  problem?: string;
  /** Why the composition was refused, in the refusal's own words. */
  refusal?: string;
  /** Whether a plane is up in this process. */
  running: boolean;
}

/** The Node runtime under a plugin plane. */
export interface PluginRuntimeStatus {
  /**
   * How many entries `kernelPlugins` asks for. Zero is a normal state,
   * not a problem — the section is opt-in.
   *
   * A count, not a boolean: nothing on the page ever read it as a flag.
   */
  configuredPlugins: number;
  /** Whether `rebon node install` could fix this here. */
  installable: boolean;
  /**
   * A Node that was found and turned down for its version.
   *
   * Separate from `problem` because it is a different situation with a
   * different fix.
   */
  outOfRange?: OutOfRangeRuntime;
  /** The resolver's own words for why nothing resolved. */
  problem?: string;
  /** The runtime that resolved, or `null` if none did. */
  resolved?: ResolvedRuntime;
  /** The versions a runtime may report, as a range someone can read. */
  supported: string;
}

/**
 * `GET /api/plugins` — the plugin plane as this process sees it.
 *
 * The page's answer to "is my plugin running": what runtime it would run on,
 * what the composition asked for, what loaded, and why the rest did not.
 */
export interface PluginStatus {
  /** One per leaf the composition resolved, in load order. */
  entries: PluginEntry[];
  /** Which loop host this build carries, in one line. */
  host: string;
  /** The kernel loop vendors a session can be switched to. */
  loops: KernelLoopOption[];
  /** The plane that is actually up, if one is. */
  plane: PluginPlaneStatus;
  /** The Node runtime a composition would run on. */
  runtime: PluginRuntimeStatus;
  /**
   * Entries that could not be turned into a load request, and why.
   *
   * A plugin that starts and is then refused at every registration is a
   * worse failure than one that never starts, so each line carries its
   * reason rather than only a name.
   */
  skipped: string[];
}

export interface PromptCapabilities {
  audio?: boolean;
  embeddedContext?: boolean;
  image?: boolean;
}

/**
 * What rebon hangs at `_meta.rebon` on standard ACP messages.
 *
 * The standard shapes are fixed, and several rebon facts have to ride along
 * anyway: which cursor a `session/update` carries, which pending permission a
 * `session/request_permission` is about, the fence a `session/cancel` is only
 * valid against. ACP reserves `_meta` for exactly this, so nothing standard
 * is bent to fit.
 *
 * Every field is optional and skipped when absent, so a message that needs
 * one fact does not carry the other nine as nulls.
 */
export interface RebonMeta {
  /**
   * Makes a retry idempotent: the owner answers a repeat of the same id
   * from its recent-results memory instead of running the command twice.
   */
  commandId?: string;
  /**
   * Where in the owner's numbering a `session/update` sits.
   *
   * In `_meta` rather than in the standard params because the client's
   * de-duplication reads it (`crate::client::stream_watermark`) and the
   * standard shape has nowhere to put it.
   */
  cursor?: number;
  /**
   * Which numbering that cursor belongs to. An owner's cursors restart when
   * it does, so a cursor from a previous epoch is not comparable with this
   * one and must not be used to skip anything.
   */
  epoch?: number;
  /**
   * Free-form text alongside a permission answer.
   *
   * The standard result carries an option id and an updated input and has
   * nowhere for this, and it is not decoration: with no option selected it
   * *is* the answer.
   */
  extraText?: string;
  /**
   * What a `session/cancel` is only valid against.
   *
   * Standard `session/cancel` is a bare notification, which is fine when a
   * client and an agent share one process and cannot disagree about what is
   * running. Across a socket they can, so the cancel says which turn it
   * meant and the owner drops it if that is no longer the turn in flight.
   */
  fence?: BackgroundIpcCancelFence;
  /**
   * The job this addresses. A fence, not a routing key: a worker that has
   * been replaced must not act on a command meant for its predecessor.
   */
  jobId?: string;
  /**
   * Which pending permission a `session/request_permission` is about.
   *
   * Carried because the owner re-sends still-pending permissions to a
   * client that attached after they were raised, so the answer is merged by
   * this id rather than by which connection it arrived on.
   */
  queryId?: number;
  /** The session this addresses. */
  sessionId?: string;
  /**
   * The token a client presents on `initialize`. Checked once, when the
   * connection is established, because the connection is what it
   * authenticates.
   */
  token?: string;
  /**
   * The turn a permission, an answer or a cancel belongs to, so a stale one
   * is refused rather than applied to whatever is running now.
   */
  turnGeneration?: number;
}

/** Plain content-block wrapper. */
export interface RegularContent {
  content: ContentBlock;
  type: "content";
}

/** [`method::RELEASE_LEASE`]. */
export interface ReleaseLeaseParams {
  clientId: string;
  /**
   * Whether the user meant to be done, as opposed to merely detaching.
   *
   * Only decides how long the owner lingers, and only when this was the
   * last lease. Defaulted for the wire: a client from before this field
   * reads as `false`, which is what every release did until it existed.
   */
  deliberate?: boolean;
}

/** Request body for `session/request_permission`. */
export interface RequestPermissionParams {
  message?: string;
  metadata?: JsonValue;
  options: PermissionOption[];
  sessionId: string;
  title?: string;
  toolCall: ToolCallReference;
  toolInput?: JsonValue;
  toolName?: string;
}

/** Flat host-side outcome for `session/request_permission`. */
export interface RequestPermissionResult {
  optionId?: string;
  outcome: PermissionOutcome;
  updatedInput?: JsonValue;
}

/** Wire-format response body for `session/request_permission`. */
export interface RequestPermissionWireResult {
  outcome: RequestPermissionResult;
  updatedInput?: JsonValue;
}

/** One resolved Node. */
export interface ResolvedRuntime {
  /**
   * Where it lives, as a string: the server has a path and the wire has
   * no path type.
   */
  executable: string;
  /**
   * Which rung of the ladder answered: an explicit demand, a managed
   * install, or `PATH`.
   */
  origin: string;
  /** The version it reported. */
  version: string;
}

export interface ResourceBody {
  blob?: string;
  mimeType?: string;
  text?: string;
  uri: string;
}

export interface ResourceContent {
  resource: ResourceBody;
  type: "resource";
}

export interface ResourceLinkContent {
  annotations?: JsonValue;
  description?: string;
  mimeType?: string;
  name: string;
  size?: number;
  title?: string;
  type: "resource_link";
  uri: string;
}

/** One entry of [`RewindResponse::checkpoints`]. */
export interface RewindCheckpoint {
  /** Whether the turn finished. An unfinished one is still a checkpoint. */
  complete: boolean;
  /** The turn number, counting from the start of the session. */
  index: number;
  /**
   * The first 240 characters of the prompt, with an ellipsis when it was
   * cut.
   */
  preview: string;
  /** When it was sent, or `null` on a turn whose line carried no stamp. */
  timestamp?: string;
  /** The user message this turn began with. */
  uuid: string;
}

/** [`method::REWIND`]. */
export interface RewindParams {
  scope?: RewindScopeWire;
  userMessageUuid: string;
}

/** `GET /api/rewind` — where a session can be rewound to. */
export interface RewindResponse {
  /** The user turns, newest last. */
  checkpoints: RewindCheckpoint[];
  /**
   * Whether it can restore files too, which needs the session's host —
   * the file-history snapshots are the host's.
   */
  filesSupported: boolean;
  /** Why files cannot be restored, or `null` when they can. */
  problem?: string;
  /** Whether this server can rewind a conversation at all. */
  supported: boolean;
}

/** What a [`BackgroundIpcRequest::Rewind`] should restore. */
export type RewindScopeWire = "conversation" | "code" | "both";

/** [`method::RUN_COMMAND`]. */
export interface RunCommandParams {
  args?: string[];
  name: string;
}

/** What a slash command produced. */
export interface RunCommandResult {
  /**
   * Absent for a command that ran and printed nothing. A command that
   * *failed* is a JSON-RPC error instead, so this is never an error channel.
   */
  output?: CommandOutput;
}

/** `GET /api/info` — what this server is and what it is running. */
export interface ServerInfo {
  /** Sessions with a `session/prompt` in flight on the server right now. */
  activeTurns: string[];
  /** The config option id that selects an agent. */
  agentConfigOption: string;
  /** The agents the page may switch between. */
  agents: AgentOption[];
  /** The directory the server was started in. */
  cwd: string;
  /**
   * The handshake the mux completed, or `null` before it has.
   *
   * The mux keeps it as the JSON it received, so that is what is passed
   * on. An [`InitializeResult`] in every case that matters, and the page
   * reads it as one; typing it here would mean a decode and a re-encode
   * on a value nothing in this process looks at, and a field the agent
   * added would be dropped on the way through.
   */
  initialize?: JsonValue;
  /** The model id the runtime resolves to. */
  model: string;
  /** The provider the runtime model resolves to. */
  provider: string;
  /** Whether this server accepts steering mid-turn. */
  steering: boolean;
  /** The `rebon` build serving this page. */
  version: string;
  /** Where the page's assets came from, for the footer. */
  webUi: WebUiSource;
}

export interface SessionCapabilities {
  list?: SessionListCapability;
}

/** A method that answers nothing but "done". */
export type SessionExtAck = Record<string, JsonValue>;

/**
 * A method that takes nothing: [`method::PING`], [`method::STATUS`],
 * [`method::RECONCILE_PLUGINS`].
 *
 * A struct rather than `null` so adding a field later is not a wire break: an
 * old peer sending `{}` still decodes, and a new peer's extra key is ignored
 * rather than refused.
 */
export type SessionExtNoParams = Record<string, JsonValue>;

export interface SessionInfo {
  _meta?: Record<string, JsonValue>;
  cwd: string;
  sessionId: string;
  title?: string;
  updatedAt?: string;
}

export type SessionListCapability = Record<string, JsonValue>;

export interface SessionListResult {
  nextCursor?: string;
  sessions: SessionInfo[];
}

export interface SessionLoadResult {
  configOptions?: ConfigOption[];
  sessionId: string;
  slashCommands?: SlashCommand[];
}

export interface SessionNewResult {
  configOptions?: ConfigOption[];
  sessionId: string;
  slashCommands?: SlashCommand[];
}

export interface SessionPromptResult {
  stopReason: StopReason;
}

export interface SessionSetConfigOptionResult {
  configOptions: ConfigOption[];
}

/**
 * Everything a client must agree with the owner about (invariant I4).
 *
 * The client keeps no authoritative copy of any of it: a permission mode, a
 * model, or a busy flag that a client believes and the owner does not is the
 * bug class this whole snapshot exists to remove.
 */
export interface SessionStatusSnapshot {
  agent?: string;
  askUserQuestions?: ForegroundQuestion[];
  /** A model turn is in flight, so a client shows Stop rather than Send. */
  busy: boolean;
  clientLeases?: ClientLease[];
  cwd: string;
  effort?: string;
  jobId: string;
  lastCommandAtMs?: number;
  lastCommandError?: string;
  /**
   * The `command_id` most recently processed, and how it went. A client that
   * lost its connection mid-command reads the outcome here instead of
   * guessing whether to retry.
   */
  lastCommandId?: string;
  /**
   * The owner's MCP servers. `None` from an owner that hosts none, or one
   * from before this field existed.
   */
  mcp?: McpStatusSnapshot;
  model?: string;
  pendingPermission?: BackgroundPermissionQuerySnapshot;
  permissionMode?: string;
  planMode?: boolean;
  sessionId?: string;
  status: BackgroundJobStatus;
  /** Fences every answer and cancel against the turn it was meant for. */
  turnGeneration: number;
  updatedAtMs: number;
  usage?: SessionUsageSnapshot;
}

export interface SessionSteeringResult {
  outcome: SteeringOutcome;
}

/** Discriminated union of `session/update` notification payloads. */
export type SessionUpdate =
  | {
    content: ContentBlock;
    sessionUpdate: "agent_message_chunk";
  }
  | {
    content: ContentBlock[];
    imagePasteIds?: number[];
    sessionUpdate: "queued_user_message";
    uuid: string;
  }
  | {
    sessionUpdate: "thinking_delta";
    text: string;
  }
  | {
    sessionUpdate: "thinking_end";
  }
  | {
    content?: ToolCallContent[];
    kind: ToolKind;
    locations?: ToolCallLocation[];
    rawInput?: Record<string, JsonValue>;
    rawOutput?: Record<string, JsonValue>;
    sessionUpdate: "tool_call";
    status: ToolCallStatus;
    title: string;
    toolCallId: string;
  }
  | {
    content?: ToolCallContent[];
    locations?: ToolCallLocation[];
    rawOutput?: Record<string, JsonValue>;
    sessionUpdate: "tool_call_update";
    status?: ToolCallStatus;
    title?: string;
    toolCallId: string;
  }
  | {
    sessionUpdate: "tool_call_auto_mode_allowed";
    /**
     * Defaulted so a peer that predates the field still decodes — it
     * lands as `Unspecified` and renders the unattributed note.
     */
    source?: AutoModeAllowSource;
    toolCallId: string;
  }
  | {
    messages_before: number;
    sessionUpdate: "compacting_started";
  }
  | {
    messages_after: number;
    sessionUpdate: "compacting_done";
    used_model: boolean;
  }
  | {
    entries: PlanEntry[];
    sessionUpdate: "plan";
  }
  | {
    commands: SlashCommand[];
    sessionUpdate: "slash_commands";
  }
  | {
    configOptions: ConfigOption[];
    sessionUpdate: "config_option_update";
  }
  | {
    plan?: string;
    sessionUpdate: "context_reset";
  }
  | {
    _meta?: Record<string, JsonValue>;
    sessionUpdate: "session_info_update";
    title?: string;
    updatedAt?: string;
  }
  | {
    inputTokens?: number;
    outputTokens?: number;
    sessionUpdate: "token_usage";
  };

/** Outer envelope for the `session/update` notification. */
export interface SessionUpdateParams {
  sessionId: string;
  update: SessionUpdate;
}

/** Token spend for the session, as the status bars show it. */
export interface SessionUsageSnapshot {
  cacheCreationTokens?: number;
  cacheReadTokens?: number;
  inputTokens: number;
  outputTokens: number;
}

/**
 * [`method::SET_OPTION`].
 *
 * Separate from running the slash command a human would type, because a
 * client that wants to *set* a value should not have to compose that command
 * and the owner should not have to parse it back.
 */
export interface SetOptionParams {
  key: string;
  value: string;
}

/** [`method::SET_PERMISSION_MODE`]. `mode` is a `PermissionMode` wire value. */
export interface SetPermissionModeParams {
  mode: string;
}

/** One entry of [`SkillsResponse::skills`]. */
export interface SkillEntry {
  /** One line about what it does. */
  description: string;
  /** Whether it is switched on. */
  enabled: boolean;
  /** What its argument looks like, or `null`. */
  hint?: string;
  /** The skill's id, which is also how it is invoked. */
  name: string;
  /** The directory it was loaded from, or `null` for one that has none. */
  path?: string;
  /**
   * Where it came from: `builtin`, `user`, `project`, `managed`, `local`,
   * `flag`, `plugin`, `mcp`.
   */
  source: string;
  /** The human title. */
  title: string;
  /** Whether it appears in the `/` menu. */
  userInvocable: boolean;
}

/** `GET /api/skills`. */
export interface SkillsResponse {
  /** Every skill the registry knows, enabled or not. */
  skills: SkillEntry[];
}

export interface SlashCommand {
  aliases?: string[];
  category?: SlashCommandCategory;
  description: string;
  input?: SlashCommandInput;
  name: string;
}

/** Category tag for slash commands. */
export type SlashCommandCategory = "command" | "skill" | "agent";

export interface SlashCommandInput {
  hint?: string;
}

/** [`method::STATUS_CHANGED`]. */
export interface StatusChangedParams {
  snapshot: SessionStatusSnapshot;
}

/** [`method::STATUS`]. */
export interface StatusResult {
  snapshot: SessionStatusSnapshot;
}

/** What became of a steering request. */
export type SteeringOutcome = "injected" | "startedNewTurn";

export type StopReason = "end_turn" | "max_tokens" | "max_turn_requests" | "refusal" | "cancelled";

/** [`method::SUBSCRIBE`]. */
export interface SubscribeParams {
  /**
   * Resume from just after this cursor. Absent means "from wherever the
   * owner's ring starts", and the [`method::HELLO`] that follows says where
   * that turned out to be.
   */
  since?: number;
}

/** `SystemMessageLevel` — wire union `'info' | 'warning' | 'error'`. */
export type SystemLevel = "info" | "warning" | "error";

/**
 * `{ type: 'system', subtype, level, content, ... }`.
 *
 * Subtype-specific payloads (API error, file snapshot, compact boundary,
 * local command, …) exist on the wire but are not typed here.
 * This type only exposes the common fields the renderer reads:
 * `subtype`, `content`, `level`, `isMeta`. The rest stay on the wire
 * as extra JSON fields — they're not dropped, they just aren't
 * surfaced as typed fields here.
 */
export interface SystemMessage {
  /**
   * Present on most typed subtypes; optional so legacy rows
   * don't fail to parse.
   */
  content?: string;
  isMeta?: boolean;
  level?: SystemLevel;
  subtype: string;
  timestamp: string;
  uuid: string;
}

/** One entry of [`TasksResponse::tasks`]. */
export interface TaskEntry {
  /** Whether it was sent to the background. */
  backgrounded: boolean;
  /** ISO-8601, or `null` on a task with no start time. */
  createdAt?: string;
  /** Its latest progress line, or `null`. */
  description?: string;
  /** Why it failed, or `null`. */
  error?: string;
  /** The task id, which is what an action names. */
  id: string;
  /** What kind of task it is. */
  kind: string;
  /** Its result as text, or `null` while it runs. */
  output?: string;
  /** Where it has got to. */
  status: string;
  /** The one-line title. */
  title: string;
  /** ISO-8601, or `null` while it runs. */
  updatedAt?: string;
}

/** [`method::TASK_REPLY`]. */
export interface TaskReplyParams {
  message: string;
  taskId: string;
}

/** `GET /api/tasks` — the background tasks of one session. */
export interface TasksResponse {
  /** Newest first. */
  tasks: TaskEntry[];
}

/** Terminal handle reference inside a tool-call content payload. */
export interface TerminalContent {
  terminalId: string;
  type: "terminal";
}

export interface TextContent {
  annotations?: JsonValue;
  text: string;
  type: "text";
}

/** Content payload attached to a tool-call update — discriminated by `type`. */
export type ToolCallContent = DiffContent | TerminalContent | RegularContent;

/** File-system anchor that a tool call references. */
export interface ToolCallLocation {
  line?: number;
  path: string;
}

/** Reference to the tool call a permission request is gating. */
export interface ToolCallReference {
  toolCallId: string;
}

/** Tool call lifecycle status. */
export type ToolCallStatus = "pending" | "in_progress" | "completed" | "failed";

/** Tool kind enum used by `tool_call` updates. */
export type ToolKind = "read" | "edit" | "delete" | "move" | "search" | "execute" | "think" | "fetch" | "other";

/** Union of the two valid shapes for a tool_result `content` field. */
export type ToolResultContent = string | JsonValue[];

/**
 * Single transcript row type matched by the Rust renderer.
 *
 * `#[serde(tag = "type")]` maps directly to the wire `type` field —
 * so `{"type":"user", ...}` deserializes as `Message::User(_)`
 * for each row in a JSONL transcript file.
 */
export type TranscriptRow =
  | (UserMessage & { type: "user"; })
  | (AssistantMessage & { type: "assistant"; })
  | (AttachmentRow & { type: "attachment"; })
  | (SystemMessage & { type: "system"; })
  | {
    type: "unknown";
  };

/** [`method::TURN`]. */
export interface TurnParams {
  state: TurnStreamState;
  /**
   * Why a turn ended. Absent on the one that started, and on an end whose
   * reason the owner does not have.
   */
  stopReason?: string;
  /**
   * Why a cancel did not stop this turn.
   *
   * The turn is still running when this is set -- `state` says so. It is
   * here rather than in the answer to whoever asked, because every client
   * watching is looking at a turn that did not stop.
   */
  stopRefused?: string;
}

/** Whether a turn is in flight. */
export type TurnStreamState = "running" | "idle";

/** `GET /api/usage` — the token ledger for one session. */
export interface UsageResponse {
  /** Cache writes, on the same terms. */
  cacheCreationTokens?: number;
  /**
   * Cache reads, which only the session's own host counts. `null`
   * without one.
   */
  cacheReadTokens?: number;
  /**
   * How long the session has been open, or `null` for one this server
   * did not open.
   */
  durationMs?: number;
  /** Tokens sent, including the turn in flight. */
  inputTokens: number;
  /** Messages on disk, or `null` when the transcript could not be read. */
  messages?: number;
  /** The model the runtime resolves to. */
  model: string;
  /** Tokens received, including the turn in flight. */
  outputTokens: number;
  /**
   * Which of the two counts this is, in words, because the difference
   * matters to whoever reads the number.
   */
  problem: string;
  /** The session this counts. */
  sessionId: string;
  /** How many turns the ledger has seen. */
  turns: number;
}

/**
 * A single content block inside a user message. Dispatched by
 * the `type` discriminant: `text`, `image` or `tool_result`.
 */
export type UserContentBlock = UserTextBlock | UserImageBlock | UserToolResultBlock;

/**
 * `{ type: 'image', source: { ... } }` content block. The source
 * shape is Anthropic-SDK defined and not consumed by the renderer
 * directly here — preserved as opaque JSON so wire
 * round-trip is lossless.
 */
export interface UserImageBlock {
  source?: JsonValue;
  type: "image";
}

/**
 * Normalized user message fields consumed by the Rust renderer.
 *
 * * `uuid`, `timestamp` — row identity.
 * * `message.content` — the Anthropic content block array.
 * * `isCompactSummary` — branch to compact-summary rendering.
 * * `isMeta`, `isVisibleInTranscriptOnly` — filter hints used by
 *   user-message visibility and sticky-prompt handling.
 * * `imagePasteIds` — paste ids for `<image>` blocks.
 * * `planContent` — optional plan override path.
 */
export interface UserMessage {
  imagePasteIds?: number[];
  isCompactSummary?: boolean;
  isMeta?: boolean;
  isVisibleInTranscriptOnly?: boolean;
  message: UserMessageInner;
  planContent?: string;
  timestamp: string;
  uuid: string;
}

/**
 * The `message` sub-object on a user row. Matches the shape that the
 * Anthropic SDK's `MessageParam` wraps — a `role: 'user'` string and
 * a `content` array.
 */
export interface UserMessageInner {
  content: UserContentBlock[];
  /**
   * Absent on a hand-authored or older line; a row that says nothing
   * about its role is the role its parent row already declared, and
   * dropping it whole would lose a message a person really sent.
   */
  role?: UserRole;
}

/**
 * The `role` literal on a user message. Always `"user"` on the
 * wire; modelled as a single-variant enum so deserialization
 * rejects a *wrong* role instead of silently accepting it as `Other`.
 * A *missing* one is tolerated — see [`UserMessageInner::role`].
 */
export type UserRole = "user";

/** `{ type: 'text', text: '...' }` content block. */
export interface UserTextBlock {
  text: string;
  type: "text";
}

/**
 * `{ type: 'tool_result', tool_use_id, content, is_error? }`.
 *
 * `content` on the wire can be a string OR an array of content
 * blocks (Anthropic's nested content format). This implementation
 * accepts both via an untagged helper: strings become
 * `ToolResultContent::Text(_)`, arrays become
 * `ToolResultContent::Blocks(_)`. The renderer currently only
 * formats the string form; the Blocks form falls through to a
 * JSON-stringify display.
 */
export interface UserToolResultBlock {
  content: ToolResultContent;
  is_error?: boolean;
  tool_use_id: string;
  type: "tool_result";
}

/**
 * Where the page's own files came from.
 *
 * The two cases are not the same shape and never have been: an embedded
 * build reports the commit it was built from and a null path, and a
 * directory reports its path and no `built` key at all. Kept asymmetric on
 * purpose — adding `"built": null` to the directory case would be a change
 * to the wire.
 */
export interface WebUiSource {
  /** What the embedded build was built from. Absent for a directory. */
  built?: string;
  /** The directory being served, or `null` when embedded. */
  path?: string;
  /** `embedded` or `directory`. */
  source: string;
}
