//! What each model can actually be asked to do.
//!
//! [`vendor`](crate::vendor) answers "what shape does this wire speak" from
//! hand-written tables. This module answers the per-model questions those
//! tables never carried — which request-body modes a model accepts, what it
//! costs, which reasoning efforts it takes — from a snapshot of
//! [models.dev](https://models.dev), regenerated by
//! `scripts/sync_model_catalog.py` and committed so a build never reaches
//! the network.
//!
//! The question that made this necessary: `service_tier: "priority"` is a
//! per-model capability, not a per-endpoint one. rebon used to send it to
//! every model on an OpenAI-shaped endpoint whenever fast mode was on, so a
//! model that does not take the field (`gpt-5.5-pro`, every `o`-series
//! model) got it anyway, with nothing said to the user either way.
//! models.dev records the answer as the body each mode contributes:
//!
//! ```json
//! "modes": {"fast": {"service_tier": "priority", "cost": {...}}}
//! ```
//!
//! ## Absence is not a "no"
//!
//! The snapshot covers the vendors rebon knows how to reach, and a user can
//! point rebon at anything. So a model the catalogue has never heard of is
//! [`TierSupport::Unknown`], and callers leave it alone: only a model that
//! is *listed* and *lacks* the mode is [`TierSupport::Unsupported`]. A
//! catalogue gap must not take a working knob away from someone.
//!
//! ## One catalogue, two surfaces
//!
//! models.dev describes the **API** surface. The ChatGPT Codex backend
//! serves the same models under a plan's own rules and can be stricter —
//! its catalogue drops `gpt-5.4-mini` from the fast tier that the API
//! grants. Sending a tier that surface ignores costs nothing, so the table
//! is read the same way on both; a model the API says no to is the case
//! worth stopping, and that answer is the same on either surface.
//!
//! ## The overlay
//!
//! `rebon` ships the snapshot it was built with; `/model refresh` writes a
//! newer one to `~/.rebon/cache/models.json` and installs it here through
//! [`install_overlay`]. The overlay is consulted first and the embedded
//! snapshot backs it, so a refresh adds models without being able to lose
//! any.

use std::collections::BTreeMap;
use std::sync::{Arc, OnceLock, PoisonError, RwLock};

use serde::{Deserialize, Serialize};

use crate::vendor::ProviderVendor;

/// The committed snapshot. Regenerate with `scripts/sync_model_catalog.py`.
const EMBEDDED: &str = include_str!("../model-table/models.json");

/// Everything the catalogue knows, by provider.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ModelCatalog {
    /// Where the data came from, for `/model` to show.
    #[serde(default)]
    pub source: String,
    /// When the snapshot was taken (RFC 3339, UTC).
    #[serde(default)]
    pub generated_at: String,
    /// The leaderboard the per-model [`Score`]s came from.
    #[serde(default)]
    pub scores: Option<ScoreMeta>,
    #[serde(default)]
    pub providers: BTreeMap<String, CatalogProvider>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CatalogProvider {
    #[serde(default)]
    pub id: String,
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub doc: Option<String>,
    #[serde(default)]
    pub api: Option<String>,
    #[serde(default)]
    pub models: BTreeMap<String, CatalogModel>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CatalogModel {
    #[serde(default)]
    pub id: String,
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub family: Option<String>,
    #[serde(default)]
    pub knowledge: Option<String>,
    #[serde(default)]
    pub release_date: Option<String>,
    #[serde(default)]
    pub last_updated: Option<String>,
    #[serde(default)]
    pub reasoning: bool,
    #[serde(default)]
    pub tool_call: bool,
    #[serde(default)]
    pub attachment: bool,
    #[serde(default)]
    pub temperature: bool,
    #[serde(default)]
    pub structured_output: bool,
    #[serde(default)]
    pub open_weights: bool,
    #[serde(default)]
    pub modalities: Modalities,
    #[serde(default)]
    pub reasoning_efforts: Vec<String>,
    #[serde(default)]
    pub limit: Limit,
    #[serde(default)]
    pub cost: Option<Cost>,
    /// Optional request-body modes, keyed by the name models.dev gives
    /// them (`fast`, `pro`, …).
    #[serde(default)]
    pub modes: BTreeMap<String, ModelMode>,
    /// Where this model stands on a leaderboard, when one has rated it.
    #[serde(default)]
    pub score: Option<Score>,
}

/// One model's standing on the board named in [`ModelCatalog::scores`].
///
/// The number itself is on the board's own scale and shifts between
/// publishes, so nothing should compare it to a constant. `rank` and `of`
/// are what survive a rescale: they say where the model stands among the
/// models that were rated with it.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Score {
    #[serde(default)]
    pub value: f64,
    #[serde(default)]
    pub rank: u32,
    /// How many rows the board carried when this was taken.
    #[serde(default)]
    pub of: u32,
    /// The board's own name for the row, kept so a join can be audited.
    #[serde(default)]
    pub measured_as: String,
    /// The reasoning effort the row was measured at, when the board says.
    #[serde(default)]
    pub variant: Option<String>,
}

impl Score {
    /// Where this stands, 0.0 at the top of the board and 1.0 at the
    /// bottom. A board with no rows answers 1.0 rather than dividing by
    /// zero — the bottom, which is the side that asks for more scaffolding.
    pub fn standing(&self) -> f64 {
        if self.of == 0 {
            return 1.0;
        }
        f64::from(self.rank.saturating_sub(1)) / f64::from(self.of)
    }
}

/// Which board a snapshot's scores came from, and the credit it owes.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ScoreMeta {
    #[serde(default)]
    pub board: String,
    #[serde(default)]
    pub source: String,
    #[serde(default)]
    pub license: String,
    /// The line to print wherever these scores are shown. The board's
    /// licence requires it.
    #[serde(default)]
    pub attribution: String,
    #[serde(default)]
    pub published: Option<String>,
    #[serde(default)]
    pub count: u32,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Modalities {
    #[serde(default)]
    pub input: Vec<String>,
    #[serde(default)]
    pub output: Vec<String>,
}

#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize)]
pub struct Limit {
    #[serde(default)]
    pub context: Option<u32>,
    #[serde(default)]
    pub input: Option<u32>,
    #[serde(default)]
    pub output: Option<u32>,
}

/// Dollars per million tokens.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Cost {
    #[serde(default)]
    pub input: Option<f64>,
    #[serde(default)]
    pub output: Option<f64>,
    #[serde(default)]
    pub cache_read: Option<f64>,
    #[serde(default)]
    pub cache_write: Option<f64>,
    /// Prices that replace the base ones past a threshold — OpenAI reprices
    /// a whole request once its input crosses 272K tokens.
    #[serde(default)]
    pub tiers: Vec<CostTier>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CostTier {
    #[serde(default)]
    pub input: Option<f64>,
    #[serde(default)]
    pub output: Option<f64>,
    #[serde(default)]
    pub cache_read: Option<f64>,
    #[serde(default)]
    pub cache_write: Option<f64>,
    #[serde(default)]
    pub tier: Option<TierBound>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TierBound {
    #[serde(rename = "type", default)]
    pub kind: String,
    #[serde(default)]
    pub size: Option<u64>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ModelMode {
    /// Lifted out of `body` because it is the knob rebon gates on.
    #[serde(default)]
    pub service_tier: Option<String>,
    /// The whole body fragment this mode contributes, for the modes rebon
    /// does not model yet.
    #[serde(default)]
    pub body: Option<serde_json::Value>,
    #[serde(default)]
    pub cost: Option<Cost>,
}

/// Whether a model takes a knob — with "the catalogue has no idea" kept
/// distinct from "the catalogue says no".
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TierSupport {
    /// Listed, and the mode is there.
    Supported,
    /// Listed, and the mode is not.
    Unsupported,
    /// Not listed at all: the caller should not change what it was doing.
    Unknown,
}

impl TierSupport {
    /// Send the field unless the catalogue positively says not to.
    pub fn should_send(self) -> bool {
        !matches!(self, Self::Unsupported)
    }
}

fn embedded() -> &'static ModelCatalog {
    static PARSED: OnceLock<ModelCatalog> = OnceLock::new();
    PARSED.get_or_init(|| match serde_json::from_str(EMBEDDED) {
        Ok(catalog) => catalog,
        Err(err) => {
            // The snapshot is committed and parsed in a test, so this is a
            // build-time mistake, not a runtime condition to recover from.
            tracing::error!("rebon-api: embedded model catalogue is unreadable: {err}");
            ModelCatalog::default()
        }
    })
}

fn overlay_slot() -> &'static RwLock<Option<Arc<ModelCatalog>>> {
    static OVERLAY: OnceLock<RwLock<Option<Arc<ModelCatalog>>>> = OnceLock::new();
    OVERLAY.get_or_init(|| RwLock::new(None))
}

/// The table behind the lock is plain data and nothing panics while
/// holding the guard, so a poisoned lock is recovered rather than treated
/// as "there is no overlay" — silently falling back to the embedded
/// snapshot would make a refreshed table disappear for the rest of the run.
fn overlay() -> Option<Arc<ModelCatalog>> {
    overlay_slot()
        .read()
        .unwrap_or_else(PoisonError::into_inner)
        .clone()
}

/// Install a refreshed catalogue over the embedded one. Returns how many
/// models it carries.
pub fn install_overlay(json: &str) -> Result<usize, serde_json::Error> {
    let catalog: ModelCatalog = serde_json::from_str(json)?;
    let count = catalog
        .providers
        .values()
        .map(|provider| provider.models.len())
        .sum();
    *overlay_slot()
        .write()
        .unwrap_or_else(PoisonError::into_inner) = Some(Arc::new(catalog));
    forget_tier_answers();
    Ok(count)
}

/// Where `/model refresh` reads a newer table from.
///
/// The site serves the same shape this module parses, so a refresh is a
/// download and a parse — no version negotiation, and a malformed answer
/// leaves the embedded snapshot in place.
pub const DEFAULT_TABLE_URL: &str = "https://reboncode.ai/api/models";

/// The refresh endpoint, with `REBON_MODEL_TABLE_URL` overriding it for a
/// self-hosted mirror or a test.
pub fn table_url() -> String {
    std::env::var("REBON_MODEL_TABLE_URL")
        .ok()
        .filter(|url| !url.trim().is_empty())
        .unwrap_or_else(|| DEFAULT_TABLE_URL.to_string())
}

/// Download a table. The caller decides whether to cache and install it.
pub async fn fetch_table(url: &str) -> Result<String, String> {
    let response = reqwest::Client::new()
        .get(url)
        .header("accept", "application/json")
        .timeout(std::time::Duration::from_secs(20))
        .send()
        .await
        .map_err(|err| format!("request to {url} failed: {err}"))?;
    let status = response.status();
    let body = response
        .text()
        .await
        .map_err(|err| format!("{url} answered {status} but the body did not arrive: {err}"))?;
    if !status.is_success() {
        let preview: String = body.chars().take(200).collect();
        return Err(format!("{url} answered {status}: {preview}"));
    }
    // Parse before handing it back: a caller that writes an unparseable
    // body to the cache would break every later start.
    serde_json::from_str::<ModelCatalog>(&body)
        .map_err(|err| format!("{url} did not return a model table: {err}"))?;
    Ok(body)
}

/// Drop the overlay and go back to the embedded snapshot.
pub fn clear_overlay() {
    *overlay_slot()
        .write()
        .unwrap_or_else(PoisonError::into_inner) = None;
    forget_tier_answers();
}

/// The score board behind the catalogue in effect, when it carries one.
///
/// Surfaces that show a score must show [`ScoreMeta::attribution`] with it:
/// the board is CC-BY, and the credit is the condition of carrying it.
pub fn score_meta() -> Option<ScoreMeta> {
    if let Some(catalog) = overlay() {
        if catalog.scores.is_some() {
            return catalog.scores.clone();
        }
    }
    embedded().scores.clone()
}

/// When the catalogue in effect was generated, and where it came from.
pub fn catalog_provenance() -> (String, String) {
    match overlay() {
        Some(catalog) => (catalog.source.clone(), catalog.generated_at.clone()),
        None => (embedded().source.clone(), embedded().generated_at.clone()),
    }
}

/// The models.dev provider id for a vendor, when there is one.
///
/// Ollama is deliberately absent: a local server's catalogue is whatever
/// the user pulled, which only `/api/tags` knows.
pub fn provider_id(vendor: ProviderVendor) -> Option<&'static str> {
    Some(match vendor {
        ProviderVendor::OpenAi => "openai",
        ProviderVendor::Anthropic => "anthropic",
        ProviderVendor::Gemini => "google",
        ProviderVendor::DeepSeek => "deepseek",
        ProviderVendor::Zhipu => "zhipuai",
        ProviderVendor::Kimi => "moonshotai",
        ProviderVendor::MiniMax => "minimax",
        ProviderVendor::SiliconFlow => "siliconflow",
        ProviderVendor::Qwen => "alibaba",
        ProviderVendor::Volcengine => "volcengine",
        ProviderVendor::OpenCode => "opencode",
        ProviderVendor::Xai => "xai",
        ProviderVendor::GithubCopilot => "github-copilot",
        ProviderVendor::Ollama | ProviderVendor::Unknown => return None,
    })
}

/// Match `model` against one provider's catalogue.
///
/// The same rules as [`ProviderVendor::known_model`]: case-insensitive, a
/// Vertex `@`-suffix ignored, and a dated snapshot suffix
/// (`gpt-6-astra-20260903`) resolving to its base row.
fn lookup_in(provider: &CatalogProvider, model: &str) -> Option<CatalogModel> {
    let wanted = model.trim().to_ascii_lowercase();
    let bare = wanted.split('@').next().unwrap_or(&wanted);
    if bare.is_empty() {
        return None;
    }
    if let Some(hit) = provider
        .models
        .iter()
        .find(|(id, _)| id.eq_ignore_ascii_case(bare))
    {
        return Some(hit.1.clone());
    }
    provider
        .models
        .iter()
        .find(|(id, _)| {
            let id = id.to_ascii_lowercase();
            bare.strip_prefix(id.as_str())
                .and_then(|rest| rest.strip_prefix('-'))
                .is_some_and(|rest| {
                    !rest.is_empty() && rest.chars().all(|c| c.is_ascii_digit() || c == '-')
                })
        })
        .map(|(_, model)| model.clone())
}

fn lookup_catalog(
    catalog: &ModelCatalog,
    provider_id: Option<&str>,
    model: &str,
) -> Option<CatalogModel> {
    if let Some(id) = provider_id {
        if let Some(provider) = catalog.providers.get(id) {
            return lookup_in(provider, model);
        }
    }
    // No provider named, or one the catalogue does not carry: the id is
    // still unambiguous in practice, so take the first vendor that lists it.
    catalog
        .providers
        .values()
        .find_map(|provider| lookup_in(provider, model))
}

/// The catalogue row for `model`, preferring `provider_id`'s table.
pub fn model(provider_id: Option<&str>, model_id: &str) -> Option<CatalogModel> {
    if let Some(catalog) = overlay() {
        if let Some(found) = lookup_catalog(&catalog, provider_id, model_id) {
            return Some(found);
        }
    }
    lookup_catalog(embedded(), provider_id, model_id)
}

/// Every model one provider lists, in catalogue order.
pub fn models_for_provider(provider_id: &str) -> Vec<CatalogModel> {
    let from = |catalog: &ModelCatalog| {
        catalog
            .providers
            .get(provider_id)
            .map(|provider| provider.models.values().cloned().collect::<Vec<_>>())
            .unwrap_or_default()
    };
    match overlay() {
        Some(catalog) => {
            let models = from(&catalog);
            if models.is_empty() {
                from(embedded())
            } else {
                models
            }
        }
        None => from(embedded()),
    }
}

/// Every model a vendor lists. Empty when the vendor has no catalogue
/// (Ollama) or the id is unknown.
pub fn models_for_vendor(vendor: ProviderVendor) -> Vec<CatalogModel> {
    provider_id(vendor)
        .map(models_for_provider)
        .unwrap_or_default()
}

/// The models of `base_url`'s vendor that can actually hold a conversation.
///
/// The catalogue lists everything a vendor sells — embeddings, image and
/// speech models included — and a model picker must not offer those. The
/// filter is [`ProviderVendor::is_chat_model_id`], the same one model
/// discovery applies to a live `GET /models`.
pub fn chat_models_for_base_url(base_url: &str) -> Vec<CatalogModel> {
    let vendor = ProviderVendor::detect(base_url);
    models_for_vendor(vendor)
        .into_iter()
        .filter(|model| vendor.is_chat_model_id(&model.id))
        .collect()
}

/// Whether `model` accepts `service_tier: "<tier>"`.
///
/// See [`TierSupport`]: an unlisted model answers [`TierSupport::Unknown`],
/// never `Unsupported`.
pub fn service_tier_support(provider_id: Option<&str>, model_id: &str, tier: &str) -> TierSupport {
    let key = format!("{}|{model_id}|{tier}", provider_id.unwrap_or(""));
    if let Some(answer) = tier_answers()
        .read()
        .unwrap_or_else(PoisonError::into_inner)
        .get(&key)
    {
        return *answer;
    }
    let answer = match model(provider_id, model_id) {
        None => TierSupport::Unknown,
        Some(row) => {
            let supported = row
                .modes
                .values()
                .any(|mode| mode.service_tier.as_deref() == Some(tier));
            if supported {
                TierSupport::Supported
            } else {
                TierSupport::Unsupported
            }
        }
    };
    tier_answers()
        .write()
        .unwrap_or_else(PoisonError::into_inner)
        .insert(key, answer);
    answer
}

/// Answers already given, so the request path asks the table once per
/// model instead of once per request.
///
/// This is the table's only hot-path caller: every request body built with
/// fast mode on asks whether the model takes the tier, and answering meant
/// scanning the catalogue and cloning a row each time. The answer cannot
/// change while a process runs unless the overlay is replaced, so both
/// installers clear this.
fn tier_answers() -> &'static RwLock<BTreeMap<String, TierSupport>> {
    static ANSWERS: OnceLock<RwLock<BTreeMap<String, TierSupport>>> = OnceLock::new();
    ANSWERS.get_or_init(|| RwLock::new(BTreeMap::new()))
}

fn forget_tier_answers() {
    tier_answers()
        .write()
        .unwrap_or_else(PoisonError::into_inner)
        .clear();
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The overlay and the memo are process-wide, so the tests that install
    /// one run one at a time. Two of them racing would have each reading
    /// the other's table — a flake that looks like a caching bug.
    fn overlay_guard() -> std::sync::MutexGuard<'static, ()> {
        static LOCK: OnceLock<std::sync::Mutex<()>> = OnceLock::new();
        LOCK.get_or_init(|| std::sync::Mutex::new(()))
            .lock()
            .unwrap_or_else(PoisonError::into_inner)
    }

    #[test]
    fn the_embedded_snapshot_parses_and_carries_the_vendors_rebon_reaches() {
        let catalog = embedded();
        assert!(
            !catalog.generated_at.is_empty(),
            "snapshot has no timestamp"
        );
        for vendor in [
            ProviderVendor::OpenAi,
            ProviderVendor::Anthropic,
            ProviderVendor::DeepSeek,
        ] {
            let id = provider_id(vendor).unwrap();
            assert!(
                catalog.providers.contains_key(id),
                "snapshot is missing {id}"
            );
        }
    }

    #[test]
    fn fast_mode_support_is_read_per_model_not_per_endpoint() {
        // The two shapes that made this module necessary: both are OpenAI,
        // both reachable on the same endpoint, and only one takes the field.
        assert_eq!(
            service_tier_support(Some("openai"), "gpt-6-astra", "priority"),
            TierSupport::Supported
        );
        assert_eq!(
            service_tier_support(Some("openai"), "gpt-5.5-pro", "priority"),
            TierSupport::Unsupported
        );
    }

    /// The request path asks once per model, and a refreshed table is not
    /// answered from a stale memo.
    ///
    /// Both halves matter. Without the memo every request with fast mode on
    /// scanned the catalogue and cloned a row; without the invalidation,
    /// `/model refresh` would install a new table that the gate never saw.
    #[test]
    fn tier_answers_are_remembered_and_forgotten_with_the_overlay() {
        let _guard = overlay_guard();
        clear_overlay();
        assert_eq!(
            service_tier_support(Some("openai"), "gpt-7-nova", "priority"),
            TierSupport::Unknown
        );

        let overlay = r#"{
          "source": "test",
          "generated_at": "2026-09-09T00:00:00Z",
          "providers": {"openai": {"id": "openai", "name": "OpenAI", "models": {
            "gpt-7-nova": {"id": "gpt-7-nova", "modes": {"fast": {"service_tier": "priority"}}}
          }}}
        }"#;
        install_overlay(overlay).unwrap();
        assert_eq!(
            service_tier_support(Some("openai"), "gpt-7-nova", "priority"),
            TierSupport::Supported,
            "installing a table must not be answered from the previous one"
        );

        // The memo holds the answer, and dropping the overlay drops it.
        assert!(!tier_answers()
            .read()
            .unwrap_or_else(PoisonError::into_inner)
            .is_empty());
        clear_overlay();
        assert!(tier_answers()
            .read()
            .unwrap_or_else(PoisonError::into_inner)
            .is_empty());
        assert_eq!(
            service_tier_support(Some("openai"), "gpt-7-nova", "priority"),
            TierSupport::Unknown
        );
    }

    #[test]
    fn an_unlisted_model_is_unknown_and_keeps_the_field() {
        let support = service_tier_support(None, "some-self-hosted-thing", "priority");
        assert_eq!(support, TierSupport::Unknown);
        assert!(support.should_send());
    }

    #[test]
    fn a_dated_snapshot_suffix_resolves_to_its_row() {
        let row = model(Some("openai"), "gpt-6-astra-20260903").expect("dated id");
        assert_eq!(row.id, "gpt-6-astra");
        let cased = model(Some("openai"), "GPT-6-Astra").expect("mixed case id");
        assert_eq!(cased.id, "gpt-6-astra");
    }

    #[test]
    fn the_catalogue_carries_the_prices_the_usage_line_needs() {
        let astra = model(Some("openai"), "gpt-6-astra").expect("astra");
        let cost = astra.cost.expect("astra is priced");
        assert!(cost.input.is_some() && cost.output.is_some());
        assert!(
            cost.cache_read.is_some(),
            "cache reads are billed, not free"
        );
        assert!(
            !cost.tiers.is_empty(),
            "astra reprices past a context threshold"
        );
    }

    #[test]
    fn an_overlay_adds_models_and_can_be_dropped() {
        let _guard = overlay_guard();
        let overlay = r#"{
          "source": "test",
          "generated_at": "2026-09-09T00:00:00Z",
          "providers": {"openai": {"id": "openai", "name": "OpenAI", "models": {
            "gpt-7-nova": {"id": "gpt-7-nova", "name": "GPT-7 Nova",
              "modes": {"fast": {"service_tier": "priority"}}}
          }}}
        }"#;
        assert_eq!(install_overlay(overlay).unwrap(), 1);
        assert_eq!(
            service_tier_support(Some("openai"), "gpt-7-nova", "priority"),
            TierSupport::Supported
        );
        // The embedded snapshot still backs the overlay.
        assert!(model(Some("openai"), "gpt-6-astra").is_some());
        clear_overlay();
        assert_eq!(
            service_tier_support(Some("openai"), "gpt-7-nova", "priority"),
            TierSupport::Unknown
        );
    }

    /// Limits where `vendor::KnownModel` and models.dev genuinely disagree
    /// — not rounding, a different number — and which side is right has not
    /// been established. Listing them is the point: a new conflict fails
    /// the test below, and a resolved one has to be struck from here.
    const KNOWN_LIMIT_CONFLICTS: &[(&str, &str)] = &[
        // 200K standard vs the 1M beta context.
        ("claude-sonnet-4-5", "context"),
        ("doubao-seed-evolving", "context"),
        ("qwen3.7-plus", "output"),
        ("kimi-k3", "output"),
        ("MiniMax-M2.7", "output"),
        ("MiniMax-M2.7-highspeed", "output"),
        ("MiniMax-M2.5", "output"),
        ("MiniMax-M2.1", "output"),
    ];

    /// Two tables know a model's limits: `vendor::KnownModel`, which the
    /// prompt and pruning paths read, and this catalogue. They may cover
    /// different models, and they may round differently — vendors document
    /// 128,000 for what models.dev records as 131,072 — but a gap wider
    /// than rounding means one of them is wrong about a live model.
    #[test]
    fn the_two_tables_do_not_drift_apart_on_the_limits_they_both_carry() {
        const TOLERANCE: f64 = 0.05;
        let mut conflicts: Vec<(String, &str)> = Vec::new();
        for vendor in ProviderVendor::ALL {
            let Some(id) = provider_id(*vendor) else {
                continue;
            };
            for known in vendor.known_models() {
                let Some(row) = model(Some(id), known.id) else {
                    continue;
                };
                let pairs = [
                    ("context", row.limit.context, Some(known.context_window)),
                    ("output", row.limit.output, known.max_output_tokens),
                ];
                for (field, theirs, ours) in pairs {
                    let (Some(theirs), Some(ours)) = (theirs, ours) else {
                        continue;
                    };
                    let spread = (theirs as f64 - ours as f64).abs() / theirs.max(ours) as f64;
                    if spread > TOLERANCE
                        && !conflicts
                            .iter()
                            .any(|(id, seen)| id == known.id && *seen == field)
                    {
                        conflicts.push((known.id.to_string(), field));
                    }
                }
            }
        }
        let found: Vec<(&str, &str)> = conflicts
            .iter()
            .map(|(id, field)| (id.as_str(), *field))
            .collect();
        let mut unexpected: Vec<_> = found
            .iter()
            .filter(|entry| !KNOWN_LIMIT_CONFLICTS.contains(entry))
            .collect();
        unexpected.sort();
        assert!(
            unexpected.is_empty(),
            "vendor.rs and the model table now disagree about {unexpected:?}; \
             fix the wrong side or record it in KNOWN_LIMIT_CONFLICTS"
        );
        let resolved: Vec<_> = KNOWN_LIMIT_CONFLICTS
            .iter()
            .filter(|entry| !found.contains(entry))
            .collect();
        assert!(
            resolved.is_empty(),
            "{resolved:?} no longer disagree; drop them from KNOWN_LIMIT_CONFLICTS"
        );
    }
}
