//! The browser dictionary.
//!
//! Two objects, `zh` and `en`, with the same keys in the same order. A message
//! with placeholders becomes a typed arrow function returning a template
//! literal, because that is how the page calls it — `t.reconnectIn(seconds)`,
//! not a runtime interpolation helper.

use crate::{Locale, Placeholder, Source, Surface, REGENERATE_COMMAND};

pub fn render(source: &Source, surface: &Surface) -> String {
    let mut out = format!(
        "\
/* Generated by `{REGENERATE_COMMAND}` from `i18n/`. Do not edit by hand — a
 * change made here is overwritten by the next run, and the staleness test
 * `generated_catalogues_are_current` fails until the two agree.
 *
 * `src/i18n.ts` spreads these two objects and adds the entries that are not
 * data; see the note there. */

/* eslint-disable */
"
    );
    for (locale, name) in [(Locale::ZhCn, "zh"), (Locale::En, "en")] {
        out.push('\n');
        out.push_str(&render_dictionary(source, surface, locale, name));
    }
    out
}

fn render_dictionary(source: &Source, surface: &Surface, locale: Locale, name: &str) -> String {
    // `en` is annotated against `zh` so a drifting value type is a compile
    // error in the page rather than a surprise at runtime — the same
    // annotation the hand-written dictionary carried.
    let annotation = if name == "zh" {
        String::new()
    } else {
        ": { [K in keyof typeof zh]: (typeof zh)[K] }".to_string()
    };
    let mut out = format!("export const {name}{annotation} = {{\n");
    for (key, text) in source.entries(surface, locale) {
        let value = match source.placeholders_for(surface, key) {
            Some(placeholders) => arrow(text, placeholders, name == "zh"),
            None => string_literal(text),
        };
        out.push_str(&format!("  {key}: {value},\n"));
    }
    out.push_str("};\n");
    out
}

/// `(s: number) => \`… ${s} …\``, with the parameter types only on the
/// dictionary the page's `Dict` type is read from.
fn arrow(text: &str, placeholders: &[Placeholder], typed: bool) -> String {
    let params = placeholders
        .iter()
        .map(|placeholder| {
            if typed {
                format!("{}: {}", placeholder.name, placeholder.kind)
            } else {
                placeholder.name.clone()
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    let mut body = String::new();
    for ch in text.chars() {
        match ch {
            '`' => body.push_str("\\`"),
            '\\' => body.push_str("\\\\"),
            '$' => body.push_str("\\$"),
            c => body.push(c),
        }
    }
    // Put the interpolations back after escaping, so a literal `$` in the copy
    // stays literal and only a real placeholder becomes `${…}`.
    for placeholder in placeholders {
        body = body.replace(
            &format!("{{{}}}", placeholder.name),
            &format!("${{{}}}", placeholder.name),
        );
    }
    format!("({params}) => `{body}`")
}

fn string_literal(text: &str) -> String {
    crate::json_string(text)
}
